version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: stream2graph-postgres
    environment:
      POSTGRES_USER: stream2graph
      POSTGRES_PASSWORD: stream2graph
      POSTGRES_DB: stream2graph
    ports:
      - "5432:5432"
    volumes:
      - stream2graph-postgres:/var/lib/postgresql/data

volumes:
  stream2graph-postgres:
